employers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from employers.views import EmployerAutocomplete

urlpatterns = [ 

	url(r'^employer-autocomplete/$',EmployerAutocomplete.as_view(),name='employer_autocomplete'),
    
    url(r'^employer/create/profile/$',views.create,name='create'),
    url(r'^employer/views/$',views.employers,name='employers'),
    url(r'^employer/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^employer/view/(?P<pk>.*)/$',views.employer,name='employer'),
    url(r'^employer/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^employer/delete-selected/$', views.delete_selected_employers, name='delete_selected_employers'),
    url(r'^employer/registration/(?P<pk>.*)/$',views.create_user,name='create_user')
]

film_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^verify/$',general_views.verify,name='verify'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^app/users-accounts/', include('users.urls', namespace="users")),
    url(r'^', include('web.urls', namespace="web")),
    url(r'^web-app/employers/', include('employers.urls', namespace="employers")),
    url(r'^web-app/candidates/', include('candidates.urls', namespace="candidates")),
    url(r'^web-app/jobs/', include('jobs.urls', namespace="jobs")),
    url(r'^payments/', include('instamojo.urls', namespace="instamojo")),

    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),
    url(r'^zohoverify/verifyforzoho\.html$', TemplateView.as_view(template_name="web/verifyforzoho.html", content_type="text/html")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.password_reset),
]
handler404 = 'web.views.handler404'
handler400 = 'web.views.handler400'
handler403 = 'web.views.handler403'
handler500 = 'web.views.handler500'

web/urls.py
from django.conf.urls import url, include
import views


urlpatterns = [

    url(r'^$',views.home,name='home'),
    url(r'^about/$',views.about,name='about'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^careers/$',views.careers,name='careers'),
    url(r'^employers/$',views.employers,name='employers'),
    url(r'^candidates/$',views.candidates,name='candidates'),
    url(r'^privacy/$',views.privacy,name='privacy'),
    url(r'^employer-profile/$',views.employer_profile,name='employer_profile'),
    url(r'^candidate-profile/$',views.candidate_profile,name='candidate_profile'),
    url(r'^student-profile/$',views.student_profile,name='student_profile'),
    url(r'^candidate/(?P<pk>.*)/$',views.candidate,name='candidate'),
    url(r'^upload-cover-photo/$', views.upload_cover, name='upload_cover'),
    url(r'^upload-candidate-photo/$', views.upload_candidate_cover, name='upload_candidate_cover'),
    url(r'^promote-video/(?P<pk>.*)/$',views.promote_video,name='promote_video'),
    url(r'^promoted-video/$',views.promoted_videos,name='promoted_videos'),  
    url(r'^promoted-video/delete/(?P<pk>.*)/$',views.delete,name='delete'), 
    url(r'^promoted-video/view/(?P<pk>.*)/$',views.promoted_video,name='promoted_video'), 

    url(r'^services/$',views.services,name='services'),
]

employers/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea, Select
from django.utils.translation import ugettext_lazy as _
from employers.models import Employer


form_class = 'w-100-p t-a-c border-color-grey-400 bd-2 p-t-10 p-b-10 f-z-16 p-l-10'


class EmployerForm(forms.ModelForm):
    
    class Meta:
        model = Employer
        exclude = ['creator','updator','auto_id','a_id','is_deleted','user','is_active',]
        widgets = {
            'banner_name': TextInput(attrs={'class': form_class,'placeholder' : 'Banner Name'}),
            'banner_no' : TextInput(attrs={'class': form_class,'placeholder' : 'Banner Registration No'}),
            'film_name': TextInput(attrs={'class': form_class,'placeholder' : 'Project Tittle'}),
            'director_name': TextInput(attrs={'class': form_class,'placeholder' : 'Director'}),
            'producer_name': TextInput(attrs={'class': form_class,'placeholder' : 'Producer'}),
            'time_duration': TextInput(attrs={'class': form_class,'placeholder' : 'Project Time Duration'}),
            'language': TextInput(attrs={'class': form_class,'placeholder' : 'Language'}),
            'email': TextInput(attrs={'class': form_class,'placeholder' : 'Email'}),

            'director_phone': TextInput(attrs={'class': form_class,'placeholder' : 'Director Phone'}),
            'director_wp': TextInput(attrs={'class': form_class,'placeholder' : 'Director Whatsapp No'}),
            'producer_phone': TextInput(attrs={'class': form_class,'placeholder' : 'Producer Phone'}),
            'producer_wp': TextInput(attrs={'class': form_class,'placeholder' : 'Producer Whatsapp No'}),
            'other_name' : TextInput(attrs={'class': form_class,'placeholder' : 'Other Name'}),
            'category' : Select(attrs={'class': 'w-100-p t-a-c border-color-grey-400 p-t-10 p-b-10 f-z-16 select','placeholder':'Category'}),
                                   
        }
        error_messages = {
            'banner_name' : {
                'required' : _("Banner Name field is required."),
            },
            'film_name' : {
                'required' : _("Film Name field is required."),
            },
            'director_name' : {
                'required' : _("Director Name field is required."),
            },
            'producer_name' : {
                'required' : _("Producer Name field is required."),
            },
            'time_duration' : {
                'required' : _("Duration field is required."),
            },
            'language' : {
                'required' : _("Language field is required."),
            },
            'email' : {
                'required' : _("E-mail field is required."),
            },
            'director_phone' : {
                'required' : _("Director Phone field is required."),
            },
            'producer_wp' : {
                'required' : _("Producer Whatsapp Number field is required."),
            },
            'other_name' : {
                'required' : _("Other Name field is required."),
            },
            'category' : {
                'required' : _("Category field is required."),
            }
        }
        def __init__(self, *args, **kwargs):
            super(CandidateForm, self).__init__(*args, **kwargs)
            self.fields['state'].empty_label = None
            

employers/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
import json
from main.decorators import check_mode,ajax_required
from main.functions import generate_form_errors, get_auto_id, get_a_id
import datetime
from django.db.models import Q
from django.views.decorators.http import require_GET
from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory
from django.core import serializers
from decimal import Decimal
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
from employers.models import Employer
from employers.forms import EmployerForm
from django.contrib.auth.models import User, Group
from users.forms import RegistrationForm
import random, string
from users.functions import send_email
from dal import autocomplete
from jobs.models import JobVacancy, JobInterest
from django.contrib.auth import authenticate 
from django.contrib.auth import login as auth_login


class EmployerAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        current_shop = get_current_shop(self.request)
        items = Employer.objects.filter(is_deleted=False)

        if self.q:
            items = items.filter(Q(phone__istartswith=self.q) | 
                                 Q(name__istartswith=self.q)
                                )
    
        return items


@check_mode
def create(request):    
    
    if request.method == 'POST':
        form = EmployerForm(request.POST,request.FILES)
        
        if form.is_valid() : 
            
            auto_id = get_auto_id(Employer)
            a_id = get_a_id(Employer,request)
            #create product
            data = form.save(commit=False)
            data.auto_id = auto_id
            data.a_id = a_id 
            data.is_active = True
            data.is_reg_fee_payed = True
            data.save()
            
            return HttpResponseRedirect(reverse('employers:create_user',kwargs={'pk':data.pk}))  
        
        else:
            context = {
                "title" : "Create Shop",
                "form" : form,
                "url" : reverse('employers:create'),
                "is_need_select" : True,
            }
            return render(request,'employers/entry.html',context)
    
    else:       
        form = EmployerForm()
        
        context = {
            "title" : "Profile",
            "form" : form,
            "url" : reverse('employers:create'),
            "redirect" : True,
            "is_need_select" : True,
        }
        return render(request,'employers/entry.html',context)


@check_mode
def employers(request):
    instances = Employer.objects.filter(is_deleted=False,is_active=True)
    query = request.GET.get("q")
    if query:
        instances = instances.filter(Q(auto_id__icontains=query) | Q(banner_name__icontains=query) | Q(film_name__icontains=query) | Q(director_name__icontains=query) | Q(category__icontains=query))
        title = "Employers - %s" %query 
    context = {
        "instances" : instances,
        'title' : "Companies",

        "is_need_custom_scroll_bar" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_wave_effect" : True,
        "is_need_popup_box" : True,
    }
    return render(request,'employers/employers.html',context) 


@check_mode
def employer(request,pk):
    instance = get_object_or_404(Employer.objects.filter(pk=pk,is_deleted=False))
    context = {
        "instance" : instance,
        "title" : instance.banner_name,

        "is_need_custom_scroll_bar" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_wave_effect" : True,
        "is_need_popup_box" : True,
    }
    return render(request,'employers/employer.html',context)


@check_mode
def edit(request,pk):
    instance = get_object_or_404(Employer.objects.filter(pk=pk,is_deleted=False)) 
    is_payed = instance.is_reg_fee_payed
    if request.method == 'POST':
        response_data = {}
        form = EmployerForm(request.POST,request.FILES,instance=instance)
        
        if form.is_valid() : 
            data = form.save(commit=False)
            data.is_reg_fee_payed = is_payed 
            data.updator = request.user
            data.date_updated = datetime.datetime.now()
            data.save() 

            return HttpResponseRedirect(reverse('web:employer_profile',))  
        
        else:       
            message = generate_form_errors(form,formset=False) 
            context = {
                "title" : "Create Shop",
                "form" : form,
                "url" : reverse('employers:edit',kwargs={'pk':instance.pk}),
                "message" : message,
                "is_need_select" : True,
            }
            return render(request,'employers/entry.html',context)
    else:

        form = EmployerForm(instance=instance)
        context = {
            "form" : form,
            "title" : "Edit Profile",
            "instance" : instance,
            "url" : reverse('employers:edit',kwargs={'pk':instance.pk}),
            "is_need_select" : True,
        }
        return render(request, 'employers/entry.html', context)


@check_mode
@ajax_required
def delete(request,pk):
    instance = get_object_or_404(Employer.objects.filter(pk=pk,is_deleted=False))
    Employer.objects.filter(pk=pk).update(is_deleted=True,is_active=False,banner_name=instance.banner_name + "_deleted_" + str(instance.auto_id))
    if User.objects.filter(id=instance.user.id).exists():
        user = User.objects.get(id=instance.user.id)
        User.objects.filter(id=instance.user.id).delete()
    JobVacancy.objects.filter(is_deleted=False,employer=instance).update(is_deleted=True,is_active=False)
    JobInterest.objects.filter(is_deleted=False,vacancy__employer=instance).update(is_deleted=True,is_selected=False,is_completed=False,is_interviewed=False)

    response_data = {
        "status" : "true",
        "title" : "Successfully Deleted",
        "message" : "Employer Successfully Deleted.",
        "redirect" : "true",
        "redirect_url" : reverse('employers:employers')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@ajax_required
def delete_selected_employers(request):
    pks = request.GET.get('pk')
    if pks:
        pks = pks[:-1]
        
        pks = pks.split(',')
        for pk in pks:      
            instance = get_object_or_404(Employer.objects.filter(pk=pk,is_deleted=False)) 
            Employer.objects.filter(pk=pk).update(is_deleted=True,banner_name=instance.banner_name + "_deleted_" + str(instance.auto_id))
            
        response_data = {
            "status" : "true",
            "title" : "Successfully Deleted",
            "message" : "Selected Employer(s) Successfully Deleted.",
            "redirect" : "true",
            "redirect_url" : reverse('employers:employers')
        }
    else:
        response_data = {
            "status" : "false",
            "title" : "Nothing selected",
            "message" : "Please select some items first.",
        }
        
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
def create_user(request,pk): 
    employer = get_object_or_404(Employer.objects.filter(pk=pk))

    if request.method == "POST":
        form = RegistrationForm(request.POST)
        response_data = {} 
        message = ""  
        data = [] 
        username = request.POST.get('username')
        password = request.POST.get('password1')
        emails = request.POST.get('email')
        email = str(emails)
        error = False
        if User.objects.filter(email=email).exists():
            error = True
            message += "This email already exists."
        if employer.user:
            error = True
            message += "This candidate already has a user."
    
        if not error:
            if form.is_valid():    

                data = form.save(commit=False)
                data.email = email
                data.is_active = True
                data.save()

                instance = data
                group = Group.objects.get(name="employer")
                instance.groups.add(group)

                employer.user=data
                employer.save()
                user = authenticate(username=username, password=password)
                auth_login(request, user)
                # return HttpResponseRedirect(reverse('instamojo:payment')+"?registration=True")
                return HttpResponseRedirect(reverse('web:employer_profile'))
    
            else: 
                context = {
                    "title" : "Registration",
                    "form" : form,
                    "url" : reverse('employers:create_user',kwargs={'pk':pk})
                }
                return render(request,'registration/registration.html',context)
    
        else:      
            context = {
                "title" : "Registration",
                "form" : form,
                "url" : reverse('employers:create_user',kwargs={'pk':pk})
            }
            return render(request,'registration/registration.html',context)

    else: 
        form = RegistrationForm(initial={'email' : employer.email})
        
        context = {
            "form" : form,
            "title" : "Registration",
            "redirect" : True,
        }
    return render(request, 'registration/registration.html', context)

templates/employers/employers.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
{% load static %}

{% load main_template_tags %}
    <section id="content">
        <div class="container">
             <div class="c-header">
                <h2>{{title}}</h2>
            </div>
            
            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>
    
                <div class="ah-search">
                    <form method="get" action="{% url 'employers:employers' %}">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
    
                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>
    
                <ul class="ah-actions actions a-alt">
                   <!--  <li>
                        <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li> -->
                    
                    <li>
                        <a title="Filter" class="filter_button" href="">
                            <i class="zmdi zmdi-filter-list"></i>
                        </a>
                    </li>
                    
                    <!-- {% if instances %}
    
                        <li>
                            <a title="Select All" class="check_all" href="">
                                <i class="zmdi zmdi-select-all"></i>
                            </a>
                        </li>
                        {% if "is_superuser" or 'can_delete_employer' in user_instance.permissionlist %}
                            <li>
                                <a title="Delete selected employers" data-id="" href="{% url 'employers:delete_selected_employers' %}" data-text="{{confirm_delete_selected_message}}" data-title="Are you sure?" class="action-button reload selected-items-button">
                                    <i class="zmdi zmdi-delete"></i>
                                </a>
                            </li>
                        {% endif %}
                    {% endif %} -->
                </ul>
                
            </div>

            <div class="card">
                
                {% if instances %}
                 <div class="card-body card-padding">
                    <div class="contacts clearfix row">
                        {% load el_pagination_tags %}
                        {% paginate 21 instances %}
                        {% for instance in instances %}
                        <div class="col-md-2 col-sm-4 col-xs-6">
                            <div class="c-item">
                                <!-- <ul class="actions b-alt">
                                    <li class="dropdown">
                                        <a href="" data-toggle="dropdown">
                                            <i class="zmdi zmdi-more-vert"></i>
                                        </a>

                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <li>
                                                <a href="{% url 'employers:edit' pk=instance.pk %}">Edit</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'employers:employer' pk=instance.pk %}">View</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'employers:delete' pk=instance.pk %}">Delete</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul> -->
                                <div class="c-info">
                                    <strong>{{instance.banner_name|camelize}}</strong>
                                    <small>{{instance.film_name|camelize}}</small>
                                </div>
                                <div class="c-footer">
                                    <a href="{% url 'employers:employer' pk=instance.pk %}" class="waves-effect bg-color-green"><i class="zmdi zmdi-person-add"></i>View</a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                {% else %}
                    {% include 'includes/not_found.html' %}
                {% endif %}  
            </div>
            
        </div>
    </section>
{% endblock %}
{% block filter_box %}
<div class="filter-box">
     <form method="get" action="{% url 'employers:employers' %}">
        <div class="card">
            <div class="card-header">
                <h2>Filter <small></small></h2>
                <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
            </div>
            
            <div class="card-body card-padding">
                <div class="form-group fg-line">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>
                
                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
    <style>
        .bg-color-green {
            background-color: #4CAF50 !important;
            color:white !important;
        }
    </style>
{% endblock %}

templates/employers/entry.html
{% extends "web/base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
	<section id="top" class="p-t-30 p-b-30" style="background: url({{static_url}}/web/images/header.png) no-repeat scroll center center / cover">
		<div class="wrapper">
			<h2 class="f-z-25 text-color-white t-a-c">The casting is amazing, your dream become an actor.</h2>
		</div>
	</section>
	<section id="middle2" style="background: url({{static_url}}/web/images/spotlight.png) no-repeat scroll center center / cover"></section>
	<section id="bottom" class="bg-color-green p-t-15 p-b-15 box-shadow-1 t-a-c">
		<section class="wrapper p-t-30 p-b-30">
			
		</section>
	</section>
</section>
	<section id="company" class="p-t-3-p p-b-3-p">
		<section class="wrapper">
			<div class="bottom p-b-40 p-l-40 p-r-40 bg-color-white border-color-grey-400 bd-2 bd-l bd-r bd-b bz">
				<section id="bottom" class="p-t-15 p-b-15 t-a-c">
					<section class="wrapper">
						<p class="margin text-color-black t-t-u f-z-30">Enter Your details</p>
					</section>
				</section>
				<form enctype="multipart/form-data" method="post" action="{{url}}">
					{% csrf_token %}
					<p class="w-100-p p-s-r">
						{{form.banner_name}}
					</p>					
					<div>
						<p class="left p-s-r w-49-p m-r-2-p m-t-2-p">
							{{form.banner_no}}
						</p>
						<p class="left w-49-p p-s-r m-t-2-p">
							{{form.category}}
						</p>
						<p class="left p-s-r w-49-p m-r-2-p m-t-2-p">
							{{form.film_name}}
						</p>
						<p class="left m-t-2-p w-49-p p-s-r">
							{{form.language}}
						</p>
						<p class="left p-s-r w-49-p m-r-2-p m-t-2-p">
							{{form.director_name}}
						</p>
						<p class="left m-t-2-p w-49-p p-s-r">
							{{form.producer_name}}
						</p>
						<p class="left p-s-r w-49-p m-r-2-p m-t-2-p">
							{{form.director_phone}}
						</p>
						<p class="left m-t-2-p w-49-p p-s-r">
							{{form.producer_phone}}
						</p>
						<p class="left p-s-r w-49-p m-r-2-p m-t-2-p">
							{{form.director_wp}}
						</p>
						<p class="left m-t-2-p w-49-p p-s-r">
							{{form.producer_wp}}
						</p>
						<p class="left p-s-r w-49-p m-r-2-p m-t-2-p">
							{{form.email}}
						</p>
						<p class="left m-t-2-p w-49-p p-s-r">
							{{form.other_name}}
						</p>
						<p class="left p-s-r w-49-p m-r-2-p m-t-2-p">
							{{form.time_duration}}
						</p>
						<p class="w-49-p left file two border-color-grey-400 bd-2 p-s-r bz m-t-2-p"> 
							<label class="p-s-a p-l-25 t-10 text-color-grey-600" for="">Banner image</label>
							<label style="border-left: 2px solid #BDBDBD;background: #4CAF50 !important;" class="p-l-20 p-r-20 p-t-10 p-b-10 right border-color-grey-400 f-z-16 text-color-white p-s-r" id="#bb">Upload Photo
						    	<input type="file" id="File"  size="60" name='fefco_registration'>
						    </label>
						    <br class="clear">
						    <b class="logo o-f-h text-color-grey-400 f-z-16 p-s-a l-0-p r-0-p t-0-p b-0-p m-a t-a-c w-100 h-25 w-45-p"></b>
						</p>
						<p class="left p-s-r w-100-p m-r-2-p m-t-2-p">
							<label class="container">I agree to the Terms of Services and Privacy Policy
							  <input type="checkbox" class='agree'>
							  <span class="checkmark"></span>
							</label>
						</p>
						<br class="clear">
					</div>
					<div class="t-a-r m-t-2-p">
						<input type='submit' name='submit' value="Submit" class="text-color-white d-i-b f-z-20 p-l-40 p-r-40 p-t-8 p-b-8 c-p bg-color-green border-color-green bd-1" />
					</div>
				</form><!--(#login > form)-->
			</div>
		</section>
	</section>
</section>
</section>
	<style>
		#company div.bottom {
			margin-top: -500px;
		}
	</style>
	<script>
		$('input[type=file]').change(function () {
		    var file_name = (this.files[0].name);
		    $('.file .logo').html(file_name);

		});
		$(document).ready(function(){
			$(".selectpicker").selectOrDie();
		});
		$(':input[type="submit"]').prop('disabled', true);
		$(document).on('change', '.agree',function() {
		    var $this = $(this);
			var checked = $this.prop('checked');
			if (checked) {
				$(':input[type="submit"]').prop('disabled', false);
			}
			else {
				$(':input[type="submit"]').prop('disabled', true);
			}

		});

	</script>
{% endblock %}