employers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views
from employers.views import EmployerAutocomplete

urlpatterns = [ 

	url(r'^employer-autocomplete/$',EmployerAutocomplete.as_view(),name='employer_autocomplete'),
    
    url(r'^employer/create/profile/$',views.create,name='create'),
    url(r'^employer/views/$',views.employers,name='employers'),
    url(r'^employer/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^employer/view/(?P<pk>.*)/$',views.employer,name='employer'),
    url(r'^employer/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^employer/delete-selected/$', views.delete_selected_employers, name='delete_selected_employers'),
    url(r'^employer/registration/(?P<pk>.*)/$',views.create_user,name='create_user')
]

film_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^verify/$',general_views.verify,name='verify'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^app/users-accounts/', include('users.urls', namespace="users")),
    url(r'^', include('web.urls', namespace="web")),
    url(r'^web-app/employers/', include('employers.urls', namespace="employers")),
    url(r'^web-app/candidates/', include('candidates.urls', namespace="candidates")),
    url(r'^web-app/jobs/', include('jobs.urls', namespace="jobs")),
    url(r'^payments/', include('instamojo.urls', namespace="instamojo")),

    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),
    url(r'^zohoverify/verifyforzoho\.html$', TemplateView.as_view(template_name="web/verifyforzoho.html", content_type="text/html")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.password_reset),
]
handler404 = 'web.views.handler404'
handler400 = 'web.views.handler400'
handler403 = 'web.views.handler403'
handler500 = 'web.views.handler500'

jobs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views

urlpatterns = [ 
    
    url(r'^jobs/post-job/$',views.post_job,name='post_job'),
    url(r'^jobs/views/$',views.jobs,name='jobs'),
    url(r'^jobs/edit/(?P<pk>.*)/$',views.edit,name='edit'),
    url(r'^jobs/view/(?P<pk>.*)/$',views.job,name='job'),
    url(r'^jobs/delete/(?P<pk>.*)/$',views.delete,name='delete'),
    url(r'^jobs/delete-selected/$', views.delete_selected_jobs, name='delete_selected_jobs'),
    url(r'^jobs/apply/(?P<pk>.*)/$',views.apply,name='apply'),
    url(r'^jobs/candidate-applied-jobs/views/$',views.applied_jobs,name='applied_jobs'),
    url(r'^jobs/publish/(?P<pk>.*)/$',views.publish,name='publish'),
    url(r'^jobs/select/(?P<pk>.*)/$',views.select,name='select'),
    url(r'^jobs/unselect/(?P<pk>.*)/$',views.unselect,name='unselect'),

    url(r'^jobs/get-job-applied-list/$',views.get_job_applied_list,name='get_job_applied_list'),
    url(r'^jobs/get-job-selected-list/$',views.get_job_selected_list,name='get_job_selected_list'),
    url(r'^jobs/select-candidate/$',views.select_candidate,name='select_candidate'),
    url(r'^jobs/interview-call/(?P<pk>.*)/$',views.interview_call,name='interview_call'),
]

web/urls.py
from django.conf.urls import url, include
import views


urlpatterns = [

    url(r'^$',views.home,name='home'),
    url(r'^about/$',views.about,name='about'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^careers/$',views.careers,name='careers'),
    url(r'^employers/$',views.employers,name='employers'),
    url(r'^candidates/$',views.candidates,name='candidates'),
    url(r'^privacy/$',views.privacy,name='privacy'),
    url(r'^employer-profile/$',views.employer_profile,name='employer_profile'),
    url(r'^candidate-profile/$',views.candidate_profile,name='candidate_profile'),
    url(r'^student-profile/$',views.student_profile,name='student_profile'),
    url(r'^candidate/(?P<pk>.*)/$',views.candidate,name='candidate'),
    url(r'^upload-cover-photo/$', views.upload_cover, name='upload_cover'),
    url(r'^upload-candidate-photo/$', views.upload_candidate_cover, name='upload_candidate_cover'),
    url(r'^promote-video/(?P<pk>.*)/$',views.promote_video,name='promote_video'),
    url(r'^promoted-video/$',views.promoted_videos,name='promoted_videos'),  
    url(r'^promoted-video/delete/(?P<pk>.*)/$',views.delete,name='delete'), 
    url(r'^promoted-video/view/(?P<pk>.*)/$',views.promoted_video,name='promoted_video'), 

    url(r'^services/$',views.services,name='services'),
]

jobs/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea, Select
from django.utils.translation import ugettext_lazy as _
from jobs.models import JobVacancy
from dal import autocomplete


form_class = "w-100-p t-a-c border-color-grey-400 bd-2 p-t-10 p-b-10 f-z-16"


class JobVacancyForm(forms.ModelForm):
    
    class Meta:
        model = JobVacancy
        exclude = ['creator','updator','auto_id','a_id','is_deleted','is_active','employer']
        widgets = {
            'job_category': Select(attrs={'class': 'w-100-p t-a-c border-color-grey-400 bd-2 p-t-10 p-b-10 f-z-16 select','data-placeholder':'Select Category'}),
            'last_date': TextInput(attrs={'class': 'w-100-p t-a-c border-color-grey-400 bd-2 p-t-10 p-b-10 f-z-16 datetimepicker','placeholder' : 'Last date','autocomplete':'off'}),
            'lead_actor': TextInput(attrs={'class': form_class,'placeholder' : 'Lead Actor','autocomplete':'off'}),
            'lead_actress': TextInput(attrs={'class': form_class,'placeholder' : 'Lead Actress','autocomplete':'off'}),
            'state': Select(attrs={'class': 'w-100-p t-a-c border-color-grey-400 p-t-10 p-b-10 f-z-16 select state-slect',}),
        }
        error_messages = {
            'job_category' : {
                'required' : _("Job Category field is required."),
            },
            'last_date' : {
                'required' : _("Last date field is required."),
            },
            'lead_actor' : {
                'required' : _("Actor field is required."),
            },
            'lead_actress' : {
                'required' : _("Actress field is required."),
            },
                      
        }

    def __init__(self, *args, **kwargs):
        super(JobVacancyForm, self).__init__(*args, **kwargs)
        self.fields['job_category'].empty_label = 'Select Category',

jobs/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, HttpResponseRedirect
import json
from main.decorators import check_mode,ajax_required
from main.functions import generate_form_errors, get_auto_id, get_a_id, get_company_a_id
import datetime
from django.db.models import Q
from jobs.models import JobVacancy, JobInterest, Interview
from jobs.forms import JobVacancyForm
from employers.models import Employer
from candidates.models import Candidate
from main.decorators import role_required
from datetime import datetime
import pytz
from django.conf import settings
from django.template.loader import render_to_string
from users.functions import send_email
from jobs.functions import as_json
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET


@check_mode
def post_job(request):    
    employer = get_object_or_404(Employer.objects.filter(user=request.user))
    if request.method == 'POST':
        form = JobVacancyForm(request.POST,request.FILES)
        
        if form.is_valid() : 
            category = form.cleaned_data['job_category']
            if not JobVacancy.objects.filter(employer__user=request.user,job_category=category,is_deleted=False).exists():
                auto_id = get_auto_id(JobVacancy)
                a_id = get_company_a_id(JobVacancy,request)
                #create product
                data = form.save(commit=False)
                data.auto_id = auto_id
                data.a_id = a_id
                data.creator = request.user
                data.updator = request.user
                data.employer = employer
                data.save()
                url = reverse('web:employer_profile') + "?job_list=True"
                return HttpResponseRedirect(url)
            else:
                message = "Job already exists"
                context = {
                    "title" : "Post Job Vacancy",
                    "form" : form,
                    "url" : reverse('jobs:post_job'),
                    "is_need_select" : True,
                    "is_need_datepicker" : True,
                    "employer" : employer,
                    "message" : message,
                }
                return render(request,'web/jobs/post.html',context)
        
        else:
            message = generate_form_errors(form,formset=False)
            context = {
                "title" : "Post Job Vacancy",
                "form" : form,
                "url" : reverse('jobs:post_job'),
                "is_need_select" : True,
                "is_need_datepicker" : True,
                "employer" : employer,
                "message" : message,
            }
            return render(request,'web/jobs/post.html',context)
    
    else:       
        form = JobVacancyForm()
        context = {
            "title" : "Profile",
            "form" : form,
            "url" : reverse('jobs:post_job'),
            "redirect" : True,
            "is_need_select" : True,
            "is_need_datepicker" : True,
            "employer" : employer,
        }
        return render(request,'web/jobs/post.html',context)


@check_mode
def jobs(request):
    instances = JobVacancy.objects.filter(is_deleted=False)
    query = request.GET.get("q")
    title = "Job Vacancies"
    if query:
        instances = instances.filter(Q(auto_id__icontains=query) | Q(employer__banner_name__icontains=query) | Q(employer__film_name__icontains=query) | Q(job_category__icontains=query) | Q(last_date__icontains=query))
        title = "Job Vacancies - %s" %query 
    
    context = {
        "instances" : instances,
        'title' : title,
        
        "is_need_popup_box" : True,
        "is_need_custom_scroll_bar" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_wave_effect" : True,
    }
    return render(request,'jobs/jobs.html',context)


@check_mode
@role_required(['company','superadmin'])
def company_jobs(request):
    instances = JobVacancy.objects.filter(is_deleted=False,company__user=request.user)
    query = request.GET.get("q")
    
    context = {
        "instances" : instances,
        'title' : "Companies",

        "is_need_custom_scroll_bar" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_wave_effect" : True,
    }
    return render(request,'web/jobs/careers.html',context) 


@check_mode
def job(request,pk):
    instance = get_object_or_404(JobVacancy.objects.filter(pk=pk,is_deleted=False))
    context = {
        "instance" : instance,
        "title" : instance.name,

        "is_need_custom_scroll_bar" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_wave_effect" : True,
    }
    return render(request,'jobs/job.html',context)


@check_mode
def edit(request,pk):
    instance = get_object_or_404(JobVacancy.objects.filter(pk=pk,is_deleted=False)) 
    employer = get_object_or_404(Employer.objects.filter(user=request.user))
    if request.method == 'POST':
        form = JobVacancyForm(request.POST,request.FILES,instance=instance)
        
        if form.is_valid() : 
            
            data = form.save(commit=False)
            data.updator = request.user
            data.date_updated = datetime.now()
            data.save() 
            
            return HttpResponseRedirect(reverse('web:employer_profile'))  
        
        else:
            message = generate_form_errors(form,formset=False)
            context = {
                "title" : "Post Job Vacancy",
                "form" : form,
                "url" : reverse('jobs:edit' ,kwargs={'pk':instance.pk}),
                "employer" : employer,
                "message" : message,
                "is_need_select" : True,
                "is_need_datepicker" : True,
            }
            return render(request,'web/jobs/post.html',context)
    
    else:       
        form = JobVacancyForm(instance=instance)
        context = {
            "title" : "Profile",
            "form" : form,
            "employer" : employer,
            "url" : reverse('jobs:edit' ,kwargs={'pk':instance.pk}),
            "redirect" : True,
            "is_need_select" : True,
            "is_need_datepicker" : True,
        }
        return render(request,'web/jobs/post.html',context)


@check_mode
@ajax_required
def delete(request,pk):
    instance = get_object_or_404(JobVacancy.objects.filter(pk=pk,is_deleted=False))
    JobVacancy.objects.filter(pk=pk).update(is_deleted=True,is_active=False)
    JobInterest.objects.filter(vacancy=instance).update(is_deleted=True)
    response_data = {
        "status" : "true",
        "title" : "Successfully Deleted",
        "message" : "Job Successfully Deleted.",
        "redirect" : "true",
        "redirect_url" : reverse('web:employer_profile')
    }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@ajax_required
def delete_selected_jobs(request):
    pks = request.GET.get('pk')
    if pks:
        pks = pks[:-1]
        
        pks = pks.split(',')
        for pk in pks:      
            instance = get_object_or_404(JobVacancy.objects.filter(pk=pk,is_deleted=False)) 
            JobVacancy.objects.filter(pk=pk).update(is_deleted=True,name=instance.name + "_deleted_" + str(instance.auto_id))
            
        response_data = {
            "status" : "true",
            "title" : "Successfully Deleted",
            "message" : "Selected Job(s) Successfully Deleted.",
            "redirect" : "true",
            "redirect_url" : reverse('jobs:jobs')
        }
    else:
        response_data = {
            "status" : "false",
            "title" : "Nothing selected",
            "message" : "Please select some items first.",
        }
        
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
@ajax_required
@role_required(['candidate'])
def apply(request,pk):
    candidate = get_object_or_404(Candidate.objects.filter(user=request.user))
    vacancy = get_object_or_404(JobVacancy.objects.filter(is_deleted=False,is_active=True,pk=pk))
    #time conversion from UTC to IST
    if JobInterest.objects.filter(vacancy__pk=pk,candidate=candidate).exists():
        response_data = {
            "status" : "false",
            "title" : "Already Applied",
            "message" : "You already applied for this job.",
        }
    else:
        now = datetime.now()
        current_zone = settings.TIME_ZONE
        pre_time_zone = pytz.timezone(current_zone)
        post_time_zone = pytz.timezone('Asia/Calcutta')
        foreign_time = pre_time_zone.localize(datetime(now.year, now.month, now.day, now.hour, now.minute, now.second))
        local_time = foreign_time.astimezone(post_time_zone)
        #conversion end here
        JobInterest.objects.create(
            auto_id = get_auto_id(JobInterest),
            a_id = get_a_id(JobInterest,request),
            date_added = local_time,
            date_updated = local_time,
            vacancy = vacancy,
            candidate = candidate
        )
        response_data = {
            "status" : "true",
            "title" : "Sucess",
            "message" : "Job Successfully Applied.",
            "redirect" : "true",
            "redirect_url" : reverse('web:candidate_profile'),
        }
    return HttpResponse(json.dumps(response_data), content_type='application/javascript')


@check_mode
def applied_jobs(request):
    instances = JobInterest.objects.filter(is_deleted=False)
    query = request.GET.get("q")
    title = "Applied Job"
    if query:
        instances = instances.filter(Q(auto_id__icontains=query) | Q(vacancy__employer__banner_name__icontains=query) | Q(candidate__name__icontains=query) | Q(vacancy__employer__film_name__icontains=query) | Q(vacancy__job_category__icontains=query) | Q(vacancy__last_date__icontains=query))

templates/jobs/applied.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
	<section id="content">
        <div class="container">
             <div class="c-header">
            	<h2>{{title}}</h2>
            </div>
            
            <div class="action-header palette-theme {{current_theme}} bg clearfix">
	            <div class="ah-label hidden-xs palette-White text">{{title}}</div>
	
	            <div class="ah-search">
	            	<form method="get" action="{% url 'jobs:applied_jobs' %}" class="ahs-input">
	                    <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
	
	                    <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
	                    <input type="submit" class="hidden" />
	                </form>
	            </div>
	
	            <ul class="ah-actions actions a-alt">
	                <!-- <li>
	                    <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
	                        <i class="zmdi zmdi-search"></i>
	                    </a>
	                </li>  --> 
                    <li>
                        <a title="Filter" class="filter_button" href="">
                            <i class="zmdi zmdi-filter-list"></i>
                        </a>
                    </li>
	            </ul>
	            
	        </div>

            <div class="card">
				
				{% if instances %}
                
                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                                <th data-column-id="id" data-type="numeric">ID</th>
                                <th>Candidate</th>
                                <th>Job</th>
                                <th>Company</th>
                                <th>Category</th>
                                <th>Project Title</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% load el_pagination_tags %}
							{% paginate 21 instances %}
                        	{% for instance in instances %}
                            <tr class="check_items_row">                            	
                                <td>{{instance.a_id}}</td>
                                 <td><a href="{% url 'candidates:candidate' pk=instance.candidate.pk %}">{{instance.candidate}}</a></td>
                                <td>{{instance.vacancy}}</td>
                                <td>{{instance.vacancy.employer}}</td>  
                                <td>{{instance.vacancy.employer.category}}</td> 
                                <td>{{instance.vacancy.employer.film_name}}</td>                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                
                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                	{% get_pages %}
                	<div class="row">
                		<div class="col-sm-6">
                			<div class="pagination">
                				{% show_pages %}
                			</div>
                		</div>
                		<div class="col-sm-6 infoBar">
                			<div class="infos">
                				Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                			</div>
                		</div>
                	</div>
                </div>   
                <!--pagination-->
                {% else %}
                	{% include 'includes/not_found.html' %}
                {% endif %}            
            </div>
            
        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
	 <form method="get" action="{% url 'jobs:applied_jobs' %}">
	 	<div class="card">
			<div class="card-header">
		        <h2>Filter <small></small></h2>
		        <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
		    </div>
		    
			<div class="card-body card-padding">
			 	<div class="form-group fg-line">
		            <label>Query</label>
		            <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
		        </div>
		        
		         <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
		    </div>
		 </div>
	 </form>
</div>
{% endblock %}

{% block static %}
	{% load static %}
{% endblock %}

templates/jobs/job.html
{% extends "base.html" %}
{% load i18n %}

{% load tz %}
{% block content %}
{% load static %}
    <section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>
            
            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{instance.first_name}} {{instance.last_name}}</div>

                <ul class="ah-actions actions a-alt">
                    {% if "is_superuser" or 'can_view_staff' in user_instance.permissionlist %}
                    <li>
                        <a title="View Staffs" href="{% url 'employers:employers' %}">
                            <i class="zmdi zmdi-view-list-alt"></i>
                        </a>
                    </li>
                    {% endif %}                    
                    {% if "is_superuser" or 'can_modify_staff' in user_instance.permissionlist %}
                    <li>
                        <a title="Edit Staff" href="{% url 'employers:edit' pk=instance.pk %}">
                            <i class="zmdi zmdi-edit"></i>
                        </a>
                    </li>
                    {% endif %}
                    {% if "is_superuser" or 'can_delete_staff' in user_instance.permissionlist %}
                    <li>
                        <a title="Delete Staff" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'employers:delete' pk=instance.pk %}" class="action-button redirect">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li> 
                    {% endif %}                               
                </ul>
            </div>
             <section id="content">
                <div class="container">
                    <div class="card" id="profile-main">
                        <div class="pm-overview c-overflow">
                            <div class="pmo-pic">
                                <div class="p-relative">
                                    <a href="">                                        
                                        {% if instance.fefco_registration%}
                                                <img class="img-responsive" src="{{instance.fefco_registration.url}}" alt="" >
                                        {% else %}
                                            <img class="img-responsive" src="{% static 'img/male.png'%}" alt="">
                                        {% endif %}
                                        <img class="img-responsive" src="img/profile-pics/profile-pic-2.jpg" alt="">
                                    </a>
                                </div>


                                <div class="pmo-stat">
                                    <h2 class="m-0 c-white">{{instance.banner_name}}</h2>
                                </div>
                            </div>

                            <div class="pmo-block pmo-contact hidden-xs">
                                <h2>Contact</h2>

                                <ul>
                                    <li><i class="zmdi zmdi-account"></i> {{instance.director_name}}</li>
                                    <li><i class="zmdi zmdi-email"></i> {{instance.email}}</li>
                                    <li><i class="zmdi zmdi-globe-alt"></i> {{instance.language}}</li>
                                </ul>
                            </div>
                        </div>

                        <div class="pm-body clearfix">
                            <ul class="tab-nav tn-justified">
                                <li class="active waves-effect"><a href="profile-about.html">About</a></li>
                            </ul>
                            <div class="pmb-block">
                                <div class="pmbb-header">
                                    <h2><i class="zmdi zmdi-account m-r-5"></i> Basic Information</h2>
                                </div>
                                <div class="pmbb-body p-l-30">
                                    <div class="pmbb-view">
                                        <dl class="dl-horizontal">
                                            <dt>Name</dt>
                                            <dd>{{instance.banner_name}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Film Name</dt>
                                            <dd>{{instance.film_name}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Director Name</dt>
                                            <dd>{{instance.director_name}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Producer Name</dt>
                                            <dd>{{instance.producer_name}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Time Duration</dt>
                                            <dd>{{instance.time_duration}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Email</dt>
                                            <dd>{{instance.email}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Language</dt>
                                            <dd>{{instance.language}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Is Active</dt>
                                            <dd>{{instance.is_active}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Is Fee Payed</dt>
                                            <dd>{{instance.is_reg_fee_payed}}</dd>
                                        </dl>
                                    </div>
                                </div>
                            </div>
                            <div class="pmb-block">
                                <div class="pmbb-header">
                                    <h2><i class="zmdi zmdi-account-o m-r-5"></i>Created &amp; Updated</h2>
                                </div>
                                <div class="pmbb-body p-l-30">
                                    <div class="pmbb-view">
                                        <dl class="dl-horizontal">
                                            <dt>Date Added</dt>
                                            <dd>{{instance.date_added}}</dd>
                                        </dl>
                                        <dl class="dl-horizontal">
                                            <dt>Date Updated</dt>
                                            <dd>{{instance.date_updated}}</dd>
                                        </dl> 
                                        {% if instance.creator %}
                                        <dl class="dl-horizontal">
                                            <dt>Created User</dt>
                                            <dd>{{instance.creator.username}}</dd>
                                        </dl>  
                                        {% endif %}
                                        {% if instance.updator%}                                     
                                        <dl class="dl-horizontal">
                                            <dt>Last Updated User</dt>
                                            <dd>{{instance.updator.username}}</dd>
                                        </dl>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </section>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}