film_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.conf import settings
from registration.backends.default.views import RegistrationView
from users.forms import RegForm
from users.backend import user_created
from django.views.static import serve
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^verify/$',general_views.verify,name='verify'),
    url(r'^app/android/$',general_views.download_app,name='download_app'),
    
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^app/users-accounts/', include('users.urls', namespace="users")),
    url(r'^', include('web.urls', namespace="web")),
    url(r'^web-app/employers/', include('employers.urls', namespace="employers")),
    url(r'^web-app/candidates/', include('candidates.urls', namespace="candidates")),
    url(r'^web-app/jobs/', include('jobs.urls', namespace="jobs")),
    url(r'^payments/', include('instamojo.urls', namespace="instamojo")),

    url(r'^app/accounts/register/$', RegistrationView.as_view(form_class=RegForm),name='registration_register'),
    url(r'^zohoverify/verifyforzoho\.html$', TemplateView.as_view(template_name="web/verifyforzoho.html", content_type="text/html")),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.password_reset),
]
handler404 = 'web.views.handler404'
handler400 = 'web.views.handler400'
handler403 = 'web.views.handler403'
handler500 = 'web.views.handler500'

instamojo/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^pay$', views.payment, name='payment'),
    url(r'^payment/success/$', views.payment_success, name="payment_success"),
    url(r'^payment/failure/$', views.payment_failure, name="payment_failure"),
    url(r'^payment/cancel/$', views.payment_cancel, name="payment_cancel"),
]

web/urls.py
from django.conf.urls import url, include
import views


urlpatterns = [

    url(r'^$',views.home,name='home'),
    url(r'^about/$',views.about,name='about'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^careers/$',views.careers,name='careers'),
    url(r'^employers/$',views.employers,name='employers'),
    url(r'^candidates/$',views.candidates,name='candidates'),
    url(r'^privacy/$',views.privacy,name='privacy'),
    url(r'^employer-profile/$',views.employer_profile,name='employer_profile'),
    url(r'^candidate-profile/$',views.candidate_profile,name='candidate_profile'),
    url(r'^student-profile/$',views.student_profile,name='student_profile'),
    url(r'^candidate/(?P<pk>.*)/$',views.candidate,name='candidate'),
    url(r'^upload-cover-photo/$', views.upload_cover, name='upload_cover'),
    url(r'^upload-candidate-photo/$', views.upload_candidate_cover, name='upload_candidate_cover'),
    url(r'^promote-video/(?P<pk>.*)/$',views.promote_video,name='promote_video'),
    url(r'^promoted-video/$',views.promoted_videos,name='promoted_videos'),  
    url(r'^promoted-video/delete/(?P<pk>.*)/$',views.delete,name='delete'), 
    url(r'^promoted-video/view/(?P<pk>.*)/$',views.promoted_video,name='promoted_video'), 

    url(r'^services/$',views.services,name='services'),
]

templates/payment/failure.html
{% extends "web/base.html" %}
{% load i18n %}
{% block content %}
{% load static %}
	<section id="about">
		<section id="top" class="p-t-20 p-b-20" style="background: url({{static_url}}web/images/header.png) no-repeat scroll center center / cover">
			<div class="wrapper">
				<h2 class="f-z-25 text-color-white t-a-c">{{quote1}}</h2>
			</div>
		</section>
		<section id="middle2" style="background: url({{static_url}}web/images/spotlight.png) no-repeat scroll center center / cover">
			
		</section>
		<section id="bottom" class="bg-color-green p-t-15 p-b-15 box-shadow-1 t-a-c">
			
		</section>
	</section>
</section>
	<section class="about p-b-3-p failure">
		<section class="wrapper">
			<div class="bg-color-white p-t-50 p-b-50 p-l-40 p-r-40 border-color-black bd-l bd-r bd-b bz">
				<section id="middle">
					<section class="tabs wrapper">
						<ul class="left w-100-p">
							<li class="left bz c-p p-s-r p-t-20 p-b-20 w-100-p t-a-c active" data-tab="#tab-1"><h4 class="f-z-30 text-color-green">Payment</h4></li>
						</ul>
						<div class="hidden p-t-100 p-b-60 js-tabs-content active" id="tab-1">
							<div class="left img w-30-p"><img class="d-b w-100-p m-t-50" src="{% static 'web/images/logo.jpg' %}" alt=""></div>
							<div class="right w-60-p full">
								<p class="m-t-10 f-z-20 t-t-u f-w-b">Payment Unsuccessfull</p>
								<p class="m-b-10 f-z-18 text-color-red f-w-b">Sorry.</p>
								<p class="f-z-16 m-t-10 text-color-red">we cannot complete your payment at this time.</p>
								<p class="f-z-16 text-color-red f-w-b">Your payment has failed.</p>
								{% if true_user %}
									<a href="{% url 'web:candidate_profile' %}" class="m-t-15 text-color-white d-i-b f-z-20 p-l-40 p-r-40 p-t-8 p-b-8 c-p bg-color-green border-color-green bd-1" />Go Back</a>
								{% else %}
									<a href="{% url 'auth_logout' %}" class="m-t-15 text-color-white d-i-b f-z-20 p-l-40 p-r-40 p-t-8 p-b-8 c-p bg-color-green border-color-green bd-1" />Go Back</a>
								{% endif %}
							</div>
							<br class="clear">
						</div>
					</section>
				</section>
			</div>
		</section>
	</section>
{% endblock %}

templates/payment/index.html
<!DOCTYPE html>
<html>
<head>
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Payment Form Widget Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
		function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
	<div class="main">
		<h1>Complete Your Registration</h1>
		<div class="content">
			<div class="sap_tabs">
				<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
					<div class="resp-tabs-container">
						<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
							<div class="payment-info">
								<h3>Payment Information</h3>
								<form action="{{action}}"  name="payuform" method=POST >
									<input type="hidden" name="hash_string" value="{{hash_string}}" />
									<input type="hidden" name="key" value="{{ key }}" />            
								    <input type="hidden" name="hash" value="{{ hash }}"/>            
								    <input type="hidden" name="txnid" value="{{ txnid }}" />
								    <input type="hidden" name="amount" value="{{ amount }}" />
								    <input type="hidden" name="email" value="{{ email }}" />
								    <input type="hidden" name="firstname" value="{{ firstname }}" />
								    <input type="hidden" name="phone" value="{{ phone }}" />
								    <input type="hidden" name="productinfo" value="{{ productinfo }}"/>
								    <input type="hidden" name="surl" value="{{ surl }}"/>
								    <input type="hidden" name="furl" value="{{ furl }}" />
								    <input type="hidden" name="service_provider" value="{{ service_provider }}" />
								    <input type="hidden" name="city" value="{{ city }}" />
								    <input type="hidden" name="state" value="{{ state }}" />
								    <input type="hidden" name="address1" value="{{ address }}" />
								    <input type="hidden" name="zipcode" value="{{ zipcode }}" />
									<div class="tab-for">				
										<h5>Name</h5>
											<input type="text" value="{{firstname}}">
										<h5>Email</h5>													
											<input type="text" value="{{email}}">
										<h5>Amount</h5>													
											<input type="text" value="{{amount}}">
										<h5>Mobile</h5>													
											<input type="text" value="{{phone}}">
										<h5>Transaction ID</h5>													
											<input type="text" value="{{txnid}}">
									</div>	
									
									<input type="submit" value="PAY NOW">
								</form>
								<div class="single-bottom">
									<ul>
										<li>
											<input type="checkbox"  id="brand" value="">
											<label for="brand"><span></span>By checking this box, I agree to the Terms & Conditions & Privacy Policy.</label>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>	
				</div>
			</div>	
		</div>
	</div>
</body>
</html>

templates/payment/online_payment.html
<!DOCTYPE html>
<html>
{% load static %}
	<head>
		<!-- for-mobile-apps -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="keywords" content="Payment Form Widget Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
		Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
		<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
				function hideURLbar(){ window.scrollTo(0,1); } </script>
		<!-- //for-mobile-apps -->
		<link href="{% static 'web/payumoney/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
	</head>
	<body>
		<div class="main">
			<h1>Complete Your Registration</h1>
			<div class="content">
				<div class="sap_tabs">
					<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
						<div class="resp-tabs-container">
							<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
								<div class="payment-info">
									<h3>Checkout Page</h3>
									<form action="{{action}}"  name="payuform" method=POST >
										{% csrf_token %}
										<input type="hidden" name="hash_string" value="{{hash_string}}" />
										<input type="hidden" name="key" value="{{ key }}" />            
									    <input type="hidden" name="hash" value="{{ hash }}"/>            
									    <input type="hidden" name="txnid" value="{{ txnid }}" />
									    <input type="hidden" name="amount" value="{{ amount }}" />
									    <input type="hidden" name="email" value="{{ email }}" />
									    <input type="hidden" name="firstname" value="{{ firstname }}" />
									    <input type="hidden" name="phone" value="{{ phone }}" />
									    <input type="hidden" name="productinfo" value="{{ productinfo }}"/>
									    <input type="hidden" name="surl" value="{{ surl }}"/>
									    <input type="hidden" name="furl" value="{{ furl }}" />
									    <input type="hidden" name="service_provider" value="{{ service_provider }}" />
									    <input type="hidden" name="city" value="{{ city }}" />
									    <input type="hidden" name="state" value="{{ state }}" />
									    <input type="hidden" name="address1" value="{{ address }}" />
									    <input type="hidden" name="zipcode" value="{{ zipcode }}" />
										<div class="tab-for">				
											<h5>Name</h5>
												<input disabled type="text" value="{{firstname}}">
											<h5>Email</h5>													
												<input disabled type="text" value="{{email}}">
											<h5>Amount</h5>													
												<input disabled type="text" value="{{amount}}">
											<h5>Mobile</h5>													
												<input disabled type="text" value="{{phone}}">
											<h5>Transaction ID</h5>													
												<input disabled type="text" value="{{txnid}}">
										</div>
										<input class="payment" style="margin-bottom: 0; padding: 10px 30px; width: auto;" type="submit" value="CHECK OUT">
										{% if true_user %}
										<a class="payment" style="font-size: 16px; padding: 11px 30px; transition: 0.5s all; background: #db3236;" href="{% url 'web:candidate_profile' %}">Cancel</a>
										{% else %}
										<a class="payment" style="font-size: 16px; padding: 11px 30px; transition: 0.5s all; background: #db3236;" href="{% url 'payumoney:payment_cancel' %}">Cancel</a>
										{% endif %}
									</form>
								</div>
							</div>
						</div>	
					</div>
				</div>	
			</div>
		</div>
		<style>
			.tab-for input{
				color: #000 !important;
			}
		</style>
	</body>
</html>

templates/payment/pay.html
<form action="{% url 'instamojo:payment' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

templates/payment/payment.html
<!DOCTYPE html>
<html>
{% load static %}
	<head>
		<!-- for-mobile-apps -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="keywords" content="Payment Form Widget Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
		Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
		<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);
				function hideURLbar(){ window.scrollTo(0,1); } </script>
		<!-- //for-mobile-apps -->
		<link href="{% static 'web/payumoney/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
	</head>
	<body>
		<div class="main">
			<h1>Complete Your Registration</h1>
			<div class="content">
				<div class="sap_tabs">
					<div id="horizontalTab" style="display: block; width: 100%; margin: 0px;">
						<div class="resp-tabs-container">
							<div class="tab-1 resp-tab-content" aria-labelledby="tab_item-0">
								<div class="payment-info">
									<h3>Checkout Page</h3>
									<form action="{{url}}" method=POST >
										{% csrf_token %}
										<div class="tab-for">				
											<h5>Name</h5>
												{{form.name}}
											<h5>Email</h5>													
												{{form.email}}
											<h5>Phone</h5>													
												{{form.phone}}
											<h5>Amount</h5>													
												{{form.amount}}
											<h5>Purpose</h5>													
												{{form.purpose}}
										</div>
										<input class="payment" style="margin-bottom: 0; padding: 10px 30px; width: auto;" type="submit" value="CHECK OUT">
										{% if true_user %}
										<a class="payment" style="font-size: 16px; padding: 11px 30px; transition: 0.5s all; background: #db3236;" href="{% url 'web:candidate_profile' %}">Cancel</a>
										{% else %}
										<a class="payment" style="font-size: 16px; padding: 11px 30px; transition: 0.5s all; background: #db3236;" href="{% url 'instamojo:payment_cancel' %}">Cancel</a>
										{% endif %}
									</form>
								</div>
							</div>
						</div>	
					</div>
				</div>	
			</div>
		</div>
		<style>
			.tab-for input{
				color: #000 !important;
			}
		</style>
	</body>
</html>